src/Entity/Experience.php
<?php

namespace App\Entity;

use App\Repository\ExperienceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ExperienceRepository::class)
 */
class Experience
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $poste;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_entreprise;

        /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPoste(): ?string
    {
        return $this->poste;
    }

    public function setPoste(string $poste): self
    {
        $this->poste = $poste;

        return $this;
    }

    public function getNomEntreprise(): ?string
    {
        return $this->nom_entreprise;
    }

    public function setNomEntreprise(string $nom_entreprise): self
    {
        $this->nom_entreprise = $nom_entreprise;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }




    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/ExperienceType.php
<?php

namespace App\Form;

use App\Entity\Experience;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ExperienceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('poste', TextType::class)
            ->add('nom_entreprise', TextType::class)
            ->add('photo', TextType::class)
            ->add('lieu', TextType::class)
            ->add('date', DateType::class)
            ->add('description', TextareaType::class)
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Experience::class,
        ]);
    }
}

src/Controller/ExperienceController.php
<?php

namespace App\Controller;

use App\Entity\Experience;
use App\Form\ExperienceType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ExperienceController extends AbstractController
{
    public function __construct(EntityManagerInterface $manager){

        $this->manager = $manager;
    }
    /**
     * @Route("ajout/experience", name="app_experience_ajout")
     */
    public function index(Request $request): Response
    {
        $experience = new Experience();// 
        $formExperience= $this->createForm( ExperienceType::class,$experience);
        $formExperience->handleRequest($request);

        if($formExperience->isSubmitted() && $formExperience->isValid()){
            //recuperer l'user conecter et envoyer son prenom dans le set auteur
            //ma methode c'est de la merde je suis trop une merde la meilleur methode et de cree un get pour les deux en les concatenant direct dans la function
            // $nom= $this->getUser()->getNom();
            // $prenom= $this->getUser()->getPrenom();

            $this->manager->persist($experience);
            $this->manager->flush();

            return $this->redirectToRoute('app_home');


        }
 
        return $this->render('experience/ajoutExperience.html.twig', [
            'myExperience' => $formExperience->createView(),
        ]);
    }
    
        /**
     * @Route("/experience", name="app_experience")
     */
    public function Vue(): Response
    {
        $afficherExperience = $this->manager->getRepository(Experience::class)->findAll();
       
 
        return $this->render('experience/afficheExperience.html.twig', [
            'experience' => $afficherExperience,
        ]);
    }




        /**
     * @Route("/experience/delete/{id}", name="app_experience_delete")
     */
    public function experienceDelete(Experience $experience): Response
    {
        $this->manager->remove($experience);
        $this->manager->flush();

        return $this->redirectToRoute('app_home');
    }
    //PENSER A FAIR LE BOUTON SUPPRIMER LA COMPETENCE ET PUIS MODIFIER ETA PTRES FALLAI RECUPERER LES MSG DANS LA BASE DE DONN2E 




        /**
     * @Route("/experience/edit/{id}", name="app_experience_edit")
     */
    public function experienceEdit(Experience $experience, Request $request, SluggerInterface $slugger): Response
    {
       
       
        $formEdit= $this->createForm(ExperienceType::class,$experience);
        $formEdit->handleRequest($request);

        if($formEdit->isSubmitted() && $formEdit->isValid()){


            $this->manager->persist($experience);
            $this->manager->flush();
           return $this->redirectToRoute('app_home');
        }

        return $this->render('experience/editExperience.html.twig', [
            'editExperience' => $formEdit->createView(),
           
        ]);
}
}

templates/experience/afficheExperience.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="exp">

{% for experience in experience %}

<div class="card" style="width: 18rem;">
 <img src="{{ experience.photo}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title text-center">Card title</h5>
    <p class="card-text"> {{ experience.poste}}</p>
    <p class="card-text"> {{ experience.nomEntreprise}}</p>
    <p class="card-text"> {{ experience.lieu}}</p>
    <p class="card-text"> {{ experience.description}}</p>

{% if app.user %}
  <a href="{{ path('app_experience_edit', { id: experience.id }) }}" class="btn btn-primary">Modifier</a>  
  <a href="{{ path('app_experience_delete', { id: experience.id }) }}" class="btn btn-danger">Supprimer</a>  
{% endif %}


</div>
</div>

{% endfor %}

  </div>
{% endblock %}

templates/experience/ajoutExperience.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="cardAjout">
<div class="card" style="width: 25rem;">
  <div class="card-body" id="cardAjoutComp">
   {{form(myExperience)}}
  </div>
</div>
</div>
{% endblock %}

templates/experience/editExperience.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="cardAjout">
<div class="card" style="width: 18rem;">
  <div class="card-body" id="cardAjoutComp">
   {{form(editExperience)}}
  </div>
</div>
</div>
{% endblock %}

templates/experience/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ExperienceController!{% endblock %}

{% block body %}

<h1>Mes experiences</h1>


<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Technicien Manutentionnaire</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Technicien Manutentionnaire</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Technicien Manutentionnaire</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

</div>
{% endblock %}